env: # Environt variable to pass to all tasks
    CCACHE_DIR: /tmp/ccache
    CCACHE_EXEC: $(which ccache)
    USE_CCACHE: 1
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history

task:
    name: test
    timeout_in: 10m # Otherwise it will timeout at 60m automatically, 120m highest in free account
    container:
      image: ubuntu:20.04 
      cpu: 0.5
      memory: 1G
    ccache_cache:
      folders: 
        - /tmp/ccache
      fingerprint_key: dkdldhdkdl999
      reupload_on_changes: true
      populate_script:
        - mkdir /tmp/ccache
    test_script:
      - apt update
      - apt install -y ccache
      - ccache -M 50G 
      - ccache -z
      - env
      - mount
      - df -h
      - pwd
      - ls -lah
      - ls -lah /tmp/ccache
      - touch /tmp/ccache/test
      - cat /tmp/noexist
    on_failure:
      upload_caches:
        - ccache

task:
    name: test
    timeout_in: 2m
    container:
      image: ubuntu:20.04 
      cpu: 0.5
      memory: 1G
    ccache_cache:
      folders: 
        - test_cache
        - test1_cache
      fingerprint_key: dkdldhdkdl999
      reupload_on_changes: true
    test_script:
      - env
      - mount
      - pwd
      - ls -lah
      - ls -lah test_cache
      - ls -lah test1_cache
      - touch $PWD/test1_cache/t4

