env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history

task:
    name: task1 
    timeout_in: 2m # Otherwise it will timeout at 60m automatically, 120m highest in free account
    container:
      image: ubuntu:20.04 
      cpu: 2
      memory: 4G
    ccache_cache:
      folders: 
        - test_cache
        - test1_cache
      populate_script:
        - touch testfile1
    test_script:
      - env
      - mount
      - touch testfile2
      - pwd
      - ls -lah

task:
    name: task2
    timeout_in: 2m
    container:
      image: ubuntu:20.04 
    test_script:
      - env
      - mount
      - pwd
      - ls -lah
      - ls -lah test_cache
      - ls -lah test1_cache
      
