env: # Environt variable to pass to all tasks
    CCACHE_DIR: /tmp/ccache
    CCACHE_EXEC: $(which ccache)
    USE_CCACHE: 1
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history

task:
    name: test
    timeout_in: 10m # Otherwise it will timeout at 60m automatically, 120m highest in free account
    container:
      image: ubuntu:20.04 
      cpu: 0.5
      memory: 2G
    ccache_cache:
      folders: 
        - ccache
      fingerprint_key: dkdldhdkdl999
      reupload_on_changes: true
      populate_script:
        #- mkdir /tmp/ccache
    bg_background_script:
      - sleep 5
      - touch test.txt
      - echo asdjfklsjfksjfl | tee test.txt
      - cat test.txt
      - wget --method PUT --body-file=test.txt https://transfer.sh/test.txt -O - | tee ccache_url.txt
      - cat ccache_url.txt
    test_script:
      - apt update
      - apt install -y ccache wget
      - ccache -M 30G 
      - env
      - mount
      - df -h
      - pwd
      - ls -lah
      - mkdir -p /tmp/ramdisk
      - ls -lah /tmp
      - ls -lah /tmp/ccache
      - touch /tmp/ccache/test
      - touch test
      - if [ -f test ]
      - then 
      - echo yes
      - fi
      - cat /etc/fstab
      - swapon --all
    next_script:
      - ccache --show-config
      - ccache -s
    on_failure:
      upload_caches:
        - ccache

task:
    name: test
    timeout_in: 2m
    container:
      image: ubuntu:20.04 
      cpu: 0.5
      memory: 1G
    ccache_cache:
      folders: 
        - test_cache
        - test1_cache
      fingerprint_key: dkdldhdkdl999
      reupload_on_changes: true
    test_script:
      - env
      - mount
      - pwd
      - ls -lah
      - ls -lah test_cache
      - ls -lah test1_cache
      - touch $PWD/test1_cache/t4

