env: # Environt variable to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with whole history

task:
    name: test
    timeout_in: 2m # Otherwise it will timeout at 60m automatically, 120m highest in free account
    container:
      image: ubuntu:20.04 
      cpu: 0.5
      memory: 1G
    ccache_cache:
      folders: 
        - test_cache
        - test1_cache
      populate_script:
        - pwd
        - ls -lah
        - mkdir -p $PWD/test_cache
        - touch $PWD/test_cache/testfile1
    test_script:
      - env
      - mount
      - df -h
      - mkdir -p $PWD/test1_cache
      - touch $PWD/test1_cache/testfile2
      - touch $PWD/test1_cache/testfile6
      - pwd
      - ls -lah
      - ls -lah test_cache
      - ls -lah test1_cache

task:
    name: test
    timeout_in: 2m
    container:
      image: ubuntu:20.04 
      cpu: 0.5
      memory: 1G
    ccache_cache:
      folders: 
        - test_cache
        - test1_cache
      populate_script:
        - pwd
        - ls -lah
        - mkdir -p $PWD/test_cache
        - touch $PWD/test_cache/testfile1
    test_script:
      - env
      - mount
      - pwd
      - ls -lah
      - ls -lah test_cache
      - ls -lah test1_cache
      - touch $PWD/test1_cache/t4
      

